# Generated by Django 4.2.2 on 2023-06-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_refreshtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefreshToken',
            new_name='UserRefreshToken',
        ),
    ]
