# Generated by Django 4.2.2 on 2023-06-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_refreshtoken_userrefreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
