# Generated by Django 4.2.2 on 2023-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
